config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :reviews, path_names: {
    new: 'course/:course_id/professor/:professor_id/new',
  }
  get '/reviews/explore/course/:course_id/professor/:professor_id', to: 'reviews#explore'
  resources :professors
  root 'courses#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :professors, inverse_of: :professor
  belongs_to :user
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_and_belongs_to_many :courses, inverse_of: :course
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :course
  belongs_to :professor
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :professors
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :search_course, only: [:show, :edit, :update, :destroy]

  @professors = Professor.all.order("created_at DESC")

  def index
    @courses = Course.all.order("created_at DESC")
    respond_to do |format|
      format.html { @courses }
      format.json { render :json => @courses }
    end
  end

  def show
    respond_to do |format|
      format.html { @course }
      format.json { render :json => @course }
    end
  end

  def new
    @course = current_user.courses.build
    @professors = Professor.all.map{ |c| [c.name, c.id] }
  end
  
  def create
    @course = current_user.courses.build(course_params)

    if @course.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to course_path(@course)
    else
      render 'edit'
    end
  end

  def destroy
    @course.destroy
    redirect_to root_path
  end

  private
    def course_params
      params.require(:course).permit(:name, :professor_ids => [])
    end

    def search_course
      @course = Course.find(params[:id])
    end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :search_professor, only: [:show, :edit, :update, :destroy]

  @courses = Course.all.order("created_at DESC")

  def index
    @professors = Professor.all.order("created_at DESC")
    respond_to do |format|
      format.html { @professors }
      format.json { render :json => @professors }
    end
  end

  def show
    respond_to do |format|
      format.html { @professor }
      format.json { render :json => @professor }
    end
  end

  def new
    @professor = current_user.professors.build
  end

  def create
    @professor = current_user.professors.build(professor_params)

    if @professor.save
      redirect_to professors_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @professor.update(professor_params)
      redirect_to professor_path(@professor)
    else
      render 'edit'
    end
  end

  def destroy
    @professor.destroy
    redirect_to professors_path
  end

  private
    def professor_params
      params.require(:professor).permit(:name, :course_ids => [])
    end

    def search_professor
      @professor = Professor.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def explore
    @reviews = Review.where(:course_id => params[:course], :professor_id => params[:professor])
    respond_to do |format|
      format.html { @reviews }
      format.json { render :json => @reviews}
    end
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      course = @review.course
      redirect_to course_path(course)
    else
      Rails.logger.info("#{@review.errors.full_messages}")
      render 'new'
    end
  end

  private
    def review_params
      params.require(:review).permit(:rating, :comment, :user_id, :course_id, :professor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>
  <%= f.input :name, label: "Course Title" %>
  <% if params[:action] == "edit" %>
    <label>Professors</label>
    <br>
    <%= f.collection_check_boxes :professor_ids, Professor.all, :id, :name do |p| %>
      <%= p.label {p.check_box + p.text} %>
      <br>
    <% end %>
    <br>
  <% end %>
  <%= f.button :submit %>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h2>
<%= render 'form' %>

app/views/courses/index.html.erb
<%= javascript_pack_tag 'data_index' %>
<div id="index">
  <h1>Courses</h1>
  <h2 v-if="!courses">There are no existing courses</h2>
  <div v-else>
    <h2 v-for="course of courses">
      <a :href="'/courses/' + course.id">{{ course.name }}</a>
    </h2>
  </div>
  <br>
  <%= link_to "List of Professors", professors_path %>
</div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<h2><%= @course.name %></h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Professors</th>
      <th scope="col">Reviews</th>
    </tr>
  </thead>
  <tbody>
    <% @course.professors.each do |professor| %>
      <tr>
        <td><%= professor.name %></td>
        <td>
          <%
            ratings = Review.where(:course_id => @course.id, :professor_id => professor.id).pluck(:rating)
            average = ratings.inject { |sum, el| sum + el }.to_f / ratings.size
            average = average.nan? ? 'No reviews' : average
          %>
          <a href="/reviews/explore/course/<%= @course.id %>/professor/<%= professor.id %>"><%= average %></a>
        </td>
        <td><%= link_to "Add Review", new_review_path(course_id: @course.id, professor_id: professor.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Back", root_path %>
<% if user_signed_in? %>
  <%= link_to "Edit", edit_course_path(@course) %>
  <%= link_to "Delete", course_path(@course), method: :delete, data: { confirm: "Would you like to remove this course? " } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rate Your Prof</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Rate Your Prof", root_path, class: "navbar-brand"%>
        </div>

        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %>
            <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Add Course", new_course_path %></li>
            <li><%= link_to "Add Professor", new_professor_path %></li>
          <% end %>
      </div>
    </nav>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/professors/_form.html.erb
<%= simple_form_for @professor do |f| %>
  <%= f.input :name, label: "Professor Name" %>
  <% if params[:action] == "edit" %>
    <label>Courses</label>
    <br>
    <%= f.collection_check_boxes :course_ids, Course.all, :id, :name do |c| %>
      <%= c.label {c.check_box + c.text} %>
      <br>
    <% end %>
    <br>
  <% end %>
  <%= f.button :submit %>
<% end %>

app/views/professors/edit.html.erb
<h1>Edit Professor</h2>
<%= render 'form' %>

app/views/professors/index.html.erb
<%= javascript_pack_tag 'data_index' %>
<div id="index">
  <h1>Professors</h1>
  <h2 v-if="!professors">There are no existing professors</h2>
  <div v-else>
    <h2 v-for="professor of professors">
      <a :href="'/professors/' + professor.id">{{ professor.name }}</a>
    </h2>
  </div>
  <br>
  <%= link_to "List of Courses", courses_path %>
</div>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form' %>

app/views/professors/show.html.erb
<h2><%= @professor.name %></h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Courses</th>
      <th scope="col">Reviews</th>
    </tr>
  </thead>
  <tbody>
    <% @professor.courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td>
          <%
            ratings = Review.where(:course_id => course.id, :professor_id => @professor.id).pluck(:rating)
            average = ratings.inject { |sum, el| sum + el }.to_f / ratings.size
            average = average.nan? ? 'No reviews' : average
          %>
          <a href="/reviews/explore/course/<%= course.id %>/professor/<%= @professor.id %>"><%= average %></a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "Back", professors_path %>
<% if user_signed_in? %>
  <%= link_to "Edit", edit_professor_path(@professor) %>
  <%= link_to "Delete", professor_path(@professor), method: :delete, data: { confirm: "Would you like to remove this professor? " } %>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.input :rating, as: :radio_buttons, collection: [1, 2, 3, 4, 5] %>
  <%= f.input :comment %>
  <%= f.hidden_field :course_id, :value => params[:course_id]%>
  <%= f.hidden_field :professor_id, :value => params[:professor_id] %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/explore.html.erb
<h3>Course: <%= @course = Course.find(params[:course_id]).name %></h3>
<h3>Professor: <%= @professor = Professor.find(params[:professor_id]).name %></h3>
<% @reviews = Review.where(course_id: params[:course_id], professor_id: params[:professor_id]) %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Rating</th>
      <th scope="col">Comment</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>